
logo: /assets/img/logo.png
image: /assets/img/logo.png

timezone: Australia/Sydney
author: "Thomas Smart"
google_analytics: UA-122173386-1
title: Tom Blogs
description: 'A space for writings about IT Shenanigans'
url: 'https://thomassmart.github.io'

show_downloads: false

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

twitter:
  username: TomSmartSyd

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#Others
markdown: kramdown
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: thomassmart
