theme: jekyll-theme-cayman
timezone: Australia/Sydney
author: "Thomas Smart"
google_analytics: UA-122173386-1
title: Tom Blogs
description: 'A space for writings about Storage Spaces Direct (S2D), Infrastructure, Data Protection and other IT Shenanigans'
url: 'https://thomassmart.github.io'
baseurl: '/'

url: 'https://thomassmart.github.io'
baseurl: '/'

author:
 name: 'Thomas Smart'
 email: tom@mts.id.au
 linkedin_username:  thomassmart91

 paginate: 1
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
